#!/bin/bash

source ./user1
source ./user2
# This script shows menu to the user and the user
# can choose one task from the menu and type its number

user=$USER
echo "Welcome $user please choose a task you want to do and write its number"
while [[ true ]]; do
        echo "Menu :"
        echo "1. Show system information"
        echo "2. List users with /bin/bash shell"
        echo "3. Search for user"
        echo "4. Add user"
        echo "5. Delete user (with home backup)"
        echo "6. Show user details"
        echo "7. Change user password"
        echo "8. Lock user"
        echo "9. Unlock user"
        echo "10. Exit"
        echo "-------------------------------------------------"
        read -p "Please enter a number: " input
        case "$input" in
		1)	show_info
			;;
		2)      list_users
                        ;;
                3)      search_user
                        ;;
                4)	add_user
                        ;;
		5)	delete_user
			;;
               	6)	user_detail
                        ;;
                7)	change_password
                        ;;
                8)	lock_user
                        ;;
                9)	unlock_user
                        ;;
                10)	break;
                        ;;
                 *)	echo "can't under stand your choise please choose from the menu"
                        ;;
        esac
        echo "-------------------------------------------------"
done
